version: "2"
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "28123:8123"
      - "9000:9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse-config/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./clickhouse-config/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse-config/users.xml:/etc/clickhouse-server/users.d/users.xml
    networks:
      - ${GLOBAL_NETWORK:-kafka-clickhouse}  
